version: "3.8"
services:
  angular-nginx:
    build:
      context: ./frontend/angular-ecommerce
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: full-stack-ecommerce
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-backend:
    build:
      context: ./backend/spring-boot-ecommerce
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:7070
    depends_on:
      - mysql
